language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
  - COMPOSER_FLAGS=''

install:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script: bin/phpunit --verbose
